/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsiapp;

/**
 *
 * @author dhealf
 */
public class PanelHelpContent extends javax.swing.JPanel {

    /**
     * Creates new form PanelHelpContent
     */
    public PanelHelpContent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaHelp = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListHelp = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        txtAreaHelp.setColumns(20);
        txtAreaHelp.setRows(5);
        jScrollPane1.setViewportView(txtAreaHelp);

        ListHelp.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Quick Start", "Reasoning", "Querying", "Class Hierarcy" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListHelpMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListHelp);

        jLabel1.setText("Choose Help Topic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ListHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListHelpMouseClicked
        // TODO add your handling code here:
        if (ListHelp.getSelectedIndex() == 0) {
            txtAreaHelp.setText("Instruksi Quick Start\n"
                    + quickStart);
        } else if (ListHelp.getSelectedIndex() == 1) {
            txtAreaHelp.setText("Instruksi reasoning\n"
                    + "anda harus bla");
        } else if (ListHelp.getSelectedIndex() == 2) {
            txtAreaHelp.setText("Instruksi Querying\n"
                    + "anda harus bla");
        } else if (ListHelp.getSelectedIndex() == 2) {
            txtAreaHelp.setText("Instruksi Querying\n"
                    + "anda harus bla");
        }
    }//GEN-LAST:event_ListHelpMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAreaHelp;
    // End of variables declaration//GEN-END:variables


    String quickStart = "\nPertama kali yang harus anda lakukan dalam menggunakan aplikasi ini adalah dengan\n"
                         + "melakukan upload file ontology yang akan diproses. Apabila file berhasil diupload maka\n"
                         + "pada panel upload file akan ditampilkan teks ontologi file yang telah anda upload.\n"
                         + "";
}
