/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package skripsiapp;

import com.hp.hpl.jena.ontology.Individual;
import com.hp.hpl.jena.ontology.OntClass;
import com.hp.hpl.jena.query.Query;
import com.hp.hpl.jena.query.QueryExecution;
import com.hp.hpl.jena.query.QueryExecutionFactory;
import com.hp.hpl.jena.query.QueryFactory;
import com.hp.hpl.jena.query.QuerySolution;
import com.hp.hpl.jena.query.ResultSet;
import com.hp.hpl.jena.query.ResultSetFactory;
import com.hp.hpl.jena.query.ResultSetRewindable;
import guiSetup.ClassTree;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import oopn.Ontology;

/**
 *
 * @author dhealf
 */
public class PanelClassHierarchy extends javax.swing.JPanel {

    /**
     * Creates new form PanelClassHierarchy
     */
    public PanelClassHierarchy() {

        if (Ontology.ontologyFile != null) {
            initComponents();
        } else {
            JOptionPane.showMessageDialog(this, "Please upload your ontology file first!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        if (oopn.Ontology.tree==null){
            try{
                oopn.Ontology.tree = new ClassTree(oopn.Ontology.ontologyFilePath).getJTree();
            }
            catch(Exception e){
                //System.out.println("error tree: "+e)
            }}
            ontModelTree = oopn.Ontology.tree;
            scrol = new javax.swing.JScrollPane();
            sparqlResultsTable = new javax.swing.JTable();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            txtAddInstance = new javax.swing.JTextField();
            btnAddInstance = new javax.swing.JButton();

            ontModelTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
                public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                    ontModelTreeValueChanged(evt);
                }
            });
            jScrollPane1.setViewportView(ontModelTree);

            sparqlResultsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
            ));
            scrol.setViewportView(sparqlResultsTable);

            jLabel1.setText("HIERARCHY CLASS");

            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setText("INSTANCE");

            jLabel3.setText("Add Instance");

            btnAddInstance.setText("Save");
            btnAddInstance.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAddInstanceActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1)
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtAddInstance))
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddInstance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(scrol, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jScrollPane1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtAddInstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(btnAddInstance)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrol, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
            );
        }// </editor-fold>//GEN-END:initComponents

    private void ontModelTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_ontModelTreeValueChanged
        // TODO add your handling code here:
        int i;
        String pref;
        String[] segment = new String[10];
        System.out.println("Path : " + ontModelTree.getSelectionPath().toString());
        String[] path = ontModelTree.getSelectionPath().toString().split(",");
        for (i = 0; i < path.length; i++) {
            String[] path2 = path[i].split("#");
            segment[i] = path2[1].split("]")[0];
            System.out.println("Segment" + i + " : " + path2[1].split("]")[0]);
        }
        selectedClass = oopn.Ontology.ontologyModel.getOntClass(prefix + segment[i - 1]);
        if ("Thing".equals(segment[i - 1])) {
            pref = "owl";
        } else {
            pref = "oopn";
        }
        String queryText =
                "SELECT ?" + segment[i - 1] + " ?other_term WHERE {\n?" + segment[i - 1] + " rdf:type "+pref+":" + segment[i - 1] + "."
                + "\n?" + segment[i - 1] + " oopn:has_indonesian_term ?other_term}"
                + "ORDER BY ?" + segment[i - 1];
        String prefix = "PREFIX owl:<http://www.w3.org/2002/07/owl#>\n"
                + "PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>\n"
                + "PREFIX owl2xml:<http://www.w3.org/2006/12/owl2-xml#>\n"
                + "PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n"
                + "PREFIX oopn:<http://www.ontology.dhealf.com/pediatric/pno.owl#>\n";
        String queryString = prefix + queryText;
        System.out.println("\n" + queryString);
        System.out.println(i);
        Query query = QueryFactory.create(queryString);
        qe = QueryExecutionFactory.create(query, oopn.Ontology.ontologyModel);
        qeCopy = QueryExecutionFactory.create(query, oopn.Ontology.ontologyModel);
        resultSet = qe.execSelect();
        resultSetCopy = qeCopy.execSelect();
        // Output query results    

        //ResultSetFormatter.out(System.out, resultSet, query);
        String[] labels;
        String[][] data_table;
        ;
        int a, b, c;
        int column;
        ResultSetRewindable rsrw = ResultSetFactory.copyResults(resultSetCopy);
        int row = rsrw.size();
        System.out.println("YOUR ROW IS : "+row);

        //to get variable
        String[] varq = queryString.split("SELECT")[1].split("WHERE")[0].split("\\?");

        System.out.println(
                "List var: ");
        labels = new String[varq.length - 1];
        column = varq.length - 1;
        data_table = new String[row][column];
        for (int q = 1;
                q < varq.length;
                q++) {
            System.out.println("var : " + varq[q].trim());
            labels[q - 1] = varq[q].trim();
        }

        System.out.println(
                "column :" + column);
        System.out.println(
                "row :" + row);

        a = 0;

        while (resultSet.hasNext()) {
            QuerySolution qsol = resultSet.next();
            for (b = 0; b < column; b++) {
//                String[] as = qsol.get(labels[b]).toString().split("#");
//                data_table[a][b] = as[1].split(">")[0].replace('_', ' ');
                data_table[a][b] =qsol.get(labels[b]).toString().replace("http://www.ontology.dhealf.com/pediatric/pno.owl#", "").
                        replace("_", " ");
            }
            a++;
        }

        //sparqlResultsTable.setModel(new SparqlTableModel(resultSet));
        sparqlResultsTable.setModel(new DefaultTableModel(data_table, labels));
        qe.close();
    }//GEN-LAST:event_ontModelTreeValueChanged

    private void btnAddInstanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInstanceActionPerformed
        // TODO add your handling code here:
        System.out.println("INI INDIVIDU BARU = " + prefix + txtAddInstance.getText().trim().replace(" ", "_"));
        System.out.println("MODEL " + oopn.Ontology.ontologyModel);
        System.out.println("KELAS " + selectedClass);
        Individual individu = selectedClass.createIndividual(prefix + txtAddInstance.getText().trim().replace(" ", "_"));

        int i;
        String pref;
        String[] segment = new String[10];
        System.out.println("Path : " + ontModelTree.getSelectionPath().toString());
        String[] path = ontModelTree.getSelectionPath().toString().split(",");
        for (i = 0; i < path.length; i++) {
            String[] path2 = path[i].split("#");
            segment[i] = path2[1].split("]")[0];
            System.out.println("Segment" + i + " : " + path2[1].split("]")[0]);
        }
        selectedClass = oopn.Ontology.ontologyModel.getOntClass(prefix + segment[i - 1]);
        if (segment[i - 1] == "Thing") {
            pref = "owl";
        } else {
            pref = "oopn";
        }
        String queryText =
                "SELECT ?" + segment[i - 1] + " WHERE {\n?" + segment[i - 1] + " rdf:type oopn:" + segment[i - 1] + "}";
        String prefix = "PREFIX owl:<http://www.w3.org/2002/07/owl#>\n"
                + "PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>\n"
                + "PREFIX owl2xml:<http://www.w3.org/2006/12/owl2-xml#>\n"
                + "PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n"
                + "PREFIX oopn:<http://www.ontology.dhealf.com/pediatric/pno.owl#>\n";
        String queryString = prefix + queryText;
        System.out.println("\n" + queryString);
        System.out.println(i);
        Query query = QueryFactory.create(queryString);
        qe = QueryExecutionFactory.create(query, oopn.Ontology.ontologyModel);
        qeCopy = QueryExecutionFactory.create(query, oopn.Ontology.ontologyModel);
        resultSet = qe.execSelect();
        resultSetCopy = qeCopy.execSelect();

        System.out.println(
                "----------------------");
        System.out.println(
                "Query Result Sheet");
        System.out.println(
                "----------------------");
        // Output query results    

        //ResultSetFormatter.out(System.out, resultSet, query);
        String[] labels;
        String[][] data_table;
        ;
        int a, b, c;
        int column;
        ResultSetRewindable rsrw = ResultSetFactory.copyResults(resultSetCopy);
        int row = rsrw.size();
        System.out.println("YOUR ROW IS : "+row);
        //to get variable
        String[] varq = queryString.split("SELECT")[1].split("WHERE")[0].split("\\?");

        System.out.println(
                "List var: ");
        labels = new String[varq.length - 1];
        column = varq.length - 1;
        data_table = new String[row][column];
        for (int q = 1;
                q < varq.length;
                q++) {
            System.out.println("var : " + varq[q].trim());
            labels[q - 1] = varq[q].trim();
        }

        System.out.println(
                "column " + column);
        System.out.println(
                "row " + row);

        a = 0;

        while (resultSet.hasNext()) {
            QuerySolution qsol = resultSet.next();
            for (b = 0; b < column; b++) {
                String[] as = qsol.get(labels[b]).toString().split("#");
                data_table[a][b] = as[1].split(">")[0].replace('_', ' ');
            }
//            System.out.println("===============");
//            System.out.println("Nutrisi: " + qsol.get("Nutrisi"));
//            System.out.println("Nama Lain: " + qsol.get("lain"));
            a++;
        }

        //sparqlResultsTable.setModel(new SparqlTableModel(resultSet));
        sparqlResultsTable.setModel(new DefaultTableModel(data_table, labels));
        qe.close();
    }//GEN-LAST:event_btnAddInstanceActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddInstance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree ontModelTree;
    private javax.swing.JScrollPane scrol;
    private javax.swing.JTable sparqlResultsTable;
    private javax.swing.JTextField txtAddInstance;
    // End of variables declaration//GEN-END:variables
    ClassTree tree;
    //Dewi's code
    QueryExecution qe;
    QueryExecution qeCopy;
    ResultSet resultSet;
    ResultSet resultSetCopy;
    OntClass selectedClass;
    String prefix = "http://www.ontology.dhealf.com/pediatric/pno.owl#";

    File openOntologyFile() {
        JFileChooser fileChooser;
        File chosenFile;
        fileChooser = new JFileChooser(new File("."));
        fileChooser.showOpenDialog(fileChooser);
        chosenFile = fileChooser.getSelectedFile();
        if (chosenFile != null) {
            //loadOntologyFile(chosenFile);
        } else {
            JOptionPane.showMessageDialog(fileChooser, this);
        }
        //enableControls(true);
        return chosenFile;
    }

    public void showOntologyFile(File rdfFile, JTextArea txtAreaOntology) {
        BufferedReader reader;
        String data;
        StringBuffer allData;
        reader = null;
        allData = new StringBuffer();
        try {
            reader = new BufferedReader(new FileReader(rdfFile));
            while ((data = reader.readLine()) != null) {
                allData.append(data);
                allData.append('\n');
            }
            System.out.println(allData.toString());
            txtAreaOntology.setText(allData.toString());
        } catch (IOException ioExc) {
        }
    }
}
